# Generated by Django 5.1.7 on 2025-03-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basleshikApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_num', models.IntegerField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('compatition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basleshikApp.compatition')),
            ],
            options={
                'verbose_name': 'Sorag',
                'verbose_name_plural': 'Soraglar',
            },
        ),
    ]
